title: Adventure Thyme
description: A collection of recipes from around the world
theme: jekyll-theme-minimal

# Exclude files from processing
exclude:
  - /README.md
  - README.md
  - "*.cjs"
  - package.json
  - node_modules
  - Gemfile
  - Gemfile.lock

# Set the site's base URL
baseurl: ""

# Configure permalinks to match file structure
permalink: /posts/:title.html

# Specify where Jekyll should look for posts
collections_dir: .
collections:
  posts:
    output: true
    permalink: /posts/:name.html

defaults:
  - scope:
      path: "posts"
      type: "posts"
    values:
      layout: "default"
      permalink: /posts/:name.html