title: Adventure Thyme
description: A collection of recipes from around the world
theme: jekyll-theme-minimal

# Exclude files from processing
exclude:
  - /README.md
  - README.md
  - "*.cjs"
  - package.json
  - node_modules
  - Gemfile
  - Gemfile.lock

# Set the site's base URL
baseurl: "/adventurethyme"

# Configure permalinks for regular posts
permalink: /:title.html

# Define custom collections
collections_dir: .
include: ['posts']

# Set defaults for pages in posts directory
defaults:
  - scope:
      path: "posts"
      type: "pages"
    values:
      layout: "default"
    values:
      layout: "default"