title: Adventure Thyme
description: A collection of recipes from around the world
theme: jekyll-theme-minimal

# Exclude files from processing
exclude:
  - /README.md
  - README.md
  - "*.cjs"
  - package.json
  - node_modules
  - Gemfile
  - Gemfile.lock

# Set the site's base URL
baseurl: "/adventurethyme"

# Configure permalinks for regular posts
permalink: /:title.html

# Define custom collections
collections:
  recipes:
    output: true
    permalink: /posts/:name.html

# Set posts directory to be our recipes collection
defaults:
  - scope:
      path: ""
      type: "recipes"
    values:
      layout: "default"